bootstrap: "kafka-muhammad-45e0.aivencloud.com:17307"
topic_name: "rc.alef.iam.auth"
is_ssl: true
ca_cert_location: "/Users/a.sakharov/IdeaProjects/kafka_sender_rust/certs/ca.pem"
service_key_location: "/Users/a.sakharov/IdeaProjects/kafka_sender_rust/certs/service.cert"
key_cert_location: "/Users/a.sakharov/IdeaProjects/kafka_sender_rust/certs/service.key"